=begin
#Web API Swagger specification

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'date'

module AsposeCellsCloud

  class ImportCSVDataOption
    attr_accessor :source

    attr_accessor :import_data_type

    attr_accessor :destination_worksheet

    attr_accessor :is_insert

    attr_accessor :convert_numeric_data

    attr_accessor :first_column

    attr_accessor :source_file

    attr_accessor :first_row

    attr_accessor :separator_string

    attr_accessor :custom_parsers


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'source' => :'Source',
        :'import_data_type' => :'ImportDataType',
        :'destination_worksheet' => :'DestinationWorksheet',
        :'is_insert' => :'IsInsert',
        :'convert_numeric_data' => :'ConvertNumericData',
        :'first_column' => :'FirstColumn',
        :'source_file' => :'SourceFile',
        :'first_row' => :'FirstRow',
        :'separator_string' => :'SeparatorString',
        :'custom_parsers' => :'CustomParsers'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'source' => :'FileSource',
        :'import_data_type' => :'String',
        :'destination_worksheet' => :'String',
        :'is_insert' => :'BOOLEAN',
        :'convert_numeric_data' => :'BOOLEAN',
        :'first_column' => :'Integer',
        :'source_file' => :'String',
        :'first_row' => :'Integer',
        :'separator_string' => :'String',
        :'custom_parsers' => :'Array<CustomParserConfig>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'Source')
        self.source = attributes[:'Source']
      end

      if attributes.has_key?(:'ImportDataType')
        self.import_data_type = attributes[:'ImportDataType']
      end

      if attributes.has_key?(:'DestinationWorksheet')
        self.destination_worksheet = attributes[:'DestinationWorksheet']
      end

      if attributes.has_key?(:'IsInsert')
        self.is_insert = attributes[:'IsInsert']
      end

      if attributes.has_key?(:'ConvertNumericData')
        self.convert_numeric_data = attributes[:'ConvertNumericData']
      end

      if attributes.has_key?(:'FirstColumn')
        self.first_column = attributes[:'FirstColumn']
      end

      if attributes.has_key?(:'SourceFile')
        self.source_file = attributes[:'SourceFile']
      end

      if attributes.has_key?(:'FirstRow')
        self.first_row = attributes[:'FirstRow']
      end

      if attributes.has_key?(:'SeparatorString')
        self.separator_string = attributes[:'SeparatorString']
      end

      if attributes.has_key?(:'CustomParsers')
        if (value = attributes[:'CustomParsers']).is_a?(Array)
          self.custom_parsers = value
        end
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          source == o.source &&
          import_data_type == o.import_data_type &&
          destination_worksheet == o.destination_worksheet &&
          is_insert == o.is_insert &&
          convert_numeric_data == o.convert_numeric_data &&
          first_column == o.first_column &&
          source_file == o.source_file &&
          first_row == o.first_row &&
          separator_string == o.separator_string &&
          custom_parsers == o.custom_parsers
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [source, import_data_type, destination_worksheet, is_insert, convert_numeric_data, first_column, source_file, first_row, separator_string, custom_parsers].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = AsposeCellsCloud.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
