=begin
#Web API Swagger specification

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for AsposeCellsCloud::CellsSaveAsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CellsSaveAsApi' do
  before do
    # run before each test
    if $access_token == nil then
        conf = AsposeCellsCloud::Configuration.new
        conf.base_path = ""
        instance = AsposeCellsCloud::OAuthApi.new(AsposeCellsCloud::ApiClient.new(conf))
        $access_token = instance.o_auth_post($grant_type,$client_id,$client_secret).access_token
    end
  
    conf = AsposeCellsCloud::Configuration.new
    conf.access_token = $access_token	
    client = AsposeCellsCloud::ApiClient.new(conf)
    client.default_headers["Authorization"] ="Bearer " + $access_token
    @instance = AsposeCellsCloud::CellsSaveAsApi.new(client)
  end

  after do
    # run after each test
  end

  describe 'test an instance of CellsSaveAsApi' do
    it 'should create an instance of CellsSaveAsApi' do
      expect(@instance).to be_instance_of(AsposeCellsCloud::CellsSaveAsApi)
    end
  end

  # unit tests for cells_save_as_post_document_save_as
  # Convert document and save result to storage.
  # 
  # @param name The document name.
  # @param [Hash] opts the optional parameters
  # @option opts [SaveOptions] :save_options Save options.
  # @option opts [String] :newfilename The new file name.
  # @option opts [BOOLEAN] :is_auto_fit_rows Autofit rows.
  # @option opts [BOOLEAN] :is_auto_fit_columns Autofit columns.
  # @option opts [String] :folder The document folder.
  # @option opts [String] :storage storage name.
  # @return [SaveResponse]
  describe 'cells_save_as_post_document_save_as test' do
    it "should work" do
      name = $BOOK1
      save_options = nil
      newfilename = 'newbook.xlsx'
      is_auto_fit_rows = true
      is_auto_fit_columns = true
      folder = $TEMPFOLDER
      
      @instance.cells_save_as_post_document_save_as(name, { :save_options=>save_options, :newfilename=>newfilename, :is_auto_fit_rows=>is_auto_fit_rows, :is_auto_fit_columns=>is_auto_fit_columns, :folder=>folder})
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
  
  # unit tests for cells_save_as_post_document_save_as 
  # Convert document and save result to storage.
  # 
  # @param name The document name.
  # @param [Hash] opts the optional parameters
  # @option opts [SaveOptions] :save_options Save options.
  # @option opts [String] :newfilename The new file name.
  # @option opts [BOOLEAN] :is_auto_fit_rows Autofit rows.
  # @option opts [BOOLEAN] :is_auto_fit_columns Autofit columns.
  # @option opts [String] :folder The document folder.
  # @option opts [String] :storage storage name.
  # @return [SaveResponse]
  describe 'cells_save_as_post_document_save_as md format test' do
    it "should work" do
      name = $BOOK1
      save_options = nil
      newfilename = 'newbook.xls.md'
      is_auto_fit_rows = true
      is_auto_fit_columns = true
      folder = $TEMPFOLDER
      
      @instance.cells_save_as_post_document_save_as(name, { :save_options=>save_options, :newfilename=>newfilename, :is_auto_fit_rows=>is_auto_fit_rows, :is_auto_fit_columns=>is_auto_fit_columns, :folder=>folder})
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
