=begin
#Web API Swagger specification

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for AsposeCellsCloud::CellsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CellsBatchApi' do
  before do
    @instance = AsposeCellsCloud::CellsApi.new($client_id,$client_secret,$api_version,$baseurl)
    $VERBOSE = nil
  end

  after do
    # run after each test
  end

  describe 'cells_unit test' do
    it "should work" do
      folder = $TEMPFOLDER
      result = @instance.upload_file( folder+"/"+ $BOOK1, ::File.open(File.expand_path("data/"+ $BOOK1),"r") {|io| io.read(io.size) })
      expect(result.uploaded.size).to  be > 0
      result = @instance.upload_file( folder+"/"+$MYDOC, ::File.open(File.expand_path("data/"+$MYDOC),"r") {|io| io.read(io.size) })
      expect(result.uploaded.size).to  be > 0
      match_condition =  AsposeCellsCloud::MatchConditionRequest.new({:FullMatchConditions=>[ $BOOK1,$MYDOC]}) 
      batch_convert_request =  AsposeCellsCloud::BatchConvertRequest.new({:Format=>'pdf',:SourceFolder=>folder,:MatchCondition=>batch_convert_request})
      
      result = @instance.post_batch_convert(batch_convert_request)
      # expect(result.code).to eql(200)
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      end
  end
end

