=begin
#Web API Swagger specification

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for AsposeCellsCloud::CellsAutoshapesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CellsAutoshapesApi' do
  before do
    # run before each test
    	if $access_token == nil then
		conf = AsposeCellsCloud::Configuration.new
	    conf.base_path = ""
		instance = AsposeCellsCloud::OAuthApi.new(AsposeCellsCloud::ApiClient.new(conf))
	    $access_token = instance.o_auth_post($grant_type,$client_id,$client_secret).access_token
	end
  
    conf = AsposeCellsCloud::Configuration.new
    conf.access_token = $access_token	
	client = AsposeCellsCloud::ApiClient.new(conf)
	client.default_headers["Authorization"] ="Bearer " + $access_token
    @instance = AsposeCellsCloud::CellsAutoshapesApi.new(client)
  end

  after do
    # run after each test
  end

  describe 'test an instance of CellsAutoshapesApi' do
    it 'should create an instance of CellsAutoshapesApi' do
      expect(@instance).to be_instance_of(AsposeCellsCloud::CellsAutoshapesApi)
    end
  end

  # unit tests for cells_autoshapes_get_worksheet_autoshape
  # Get autoshape info.
  # 
  # @param name Document name.
  # @param sheet_name Worksheet name.
  # @param autoshape_number The autoshape number.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :format Exported format.
  # @option opts [String] :folder The document folder.
  # @option opts [String] :storage storage name.
  # @return [File]
  describe 'cells_autoshapes_get_worksheet_autoshape test' do
    it "should work" do
      name = $MYDOC
      sheet_name = $SHEET2
      autoshape_number = 4
      format = 'PNG'
      folder = $TEMPFOLDER
      
      @instance.cells_autoshapes_get_worksheet_autoshape(name, sheet_name, autoshape_number,  {  :format=>format,:folder=>folder})
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cells_autoshapes_get_worksheet_autoshapes
  # Get worksheet autoshapes info.
  # 
  # @param name Document name.
  # @param sheet_name The worksheet name.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :folder Document&#39;s folder.
  # @option opts [String] :storage storage name.
  # @return [AutoShapesResponse]
  describe 'cells_autoshapes_get_worksheet_autoshapes test' do
    it "should work" do
      name = $MYDOC
      sheet_name = $SHEET1
      folder = $TEMPFOLDER
      
      @instance.cells_autoshapes_get_worksheet_autoshapes(name, sheet_name,  { :folder=>folder})
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
