=begin
#Web API Swagger specification

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for AsposeCellsCloud::CellsPropertiesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CellsPropertiesApi' do
  before do
    # run before each test
    if $access_token == nil then
        conf = AsposeCellsCloud::Configuration.new
        conf.base_path = ""
        instance = AsposeCellsCloud::OAuthApi.new(AsposeCellsCloud::ApiClient.new(conf))
        $access_token = instance.o_auth_post($grant_type,$client_id,$client_secret).access_token
    end
  
    conf = AsposeCellsCloud::Configuration.new
    conf.access_token = $access_token	
    client = AsposeCellsCloud::ApiClient.new(conf)
    client.default_headers["Authorization"] ="Bearer " + $access_token

    @instance = AsposeCellsCloud::CellsPropertiesApi.new(client)
  end

  after do
    # run after each test
  end

  describe 'test an instance of CellsPropertiesApi' do
    it 'should create an instance of CellsPropertiesApi' do
      expect(@instance).to be_instance_of(AsposeCellsCloud::CellsPropertiesApi)
    end
  end

  # unit tests for cells_properties_delete_document_properties
  # Delete all custom document properties and clean built-in ones.
  # 
  # @param name The document name.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :folder The document folder.
  # @option opts [String] :storage storage name.
  # @return [CellsDocumentPropertiesResponse]
  describe 'cells_properties_delete_document_properties test' do
    it "should work" do
      name = $BOOK1
      folder = $TEMPFOLDER
      
      @instance.cells_properties_delete_document_properties(name,  { :folder=>folder})
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cells_properties_delete_document_property
  # Delete document property.
  # 
  # @param name The document name.
  # @param property_name The property name.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :folder The document folder.
  # @option opts [String] :storage storage name.
  # @return [CellsDocumentPropertiesResponse]
  describe 'cells_properties_delete_document_property test' do
    it "should work" do
      name = $BOOK1
      property_name = 'Author'
      folder = $TEMPFOLDER
      
      @instance.cells_properties_delete_document_property(name, property_name,  { :folder=>folder})
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cells_properties_get_document_properties
  # Read document properties.
  # 
  # @param name The document name.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :folder The document folder.
  # @option opts [String] :storage storage name.
  # @return [CellsDocumentPropertiesResponse]
  describe 'cells_properties_get_document_properties test' do
    it "should work" do
      name = $BOOK1
      folder = $TEMPFOLDER
      
      @instance.cells_properties_get_document_properties(name,  { :folder=>folder})
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cells_properties_get_document_property
  # Read document property by name.
  # 
  # @param name The document name.
  # @param property_name The property name.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :folder The document folder.
  # @option opts [String] :storage storage name.
  # @return [CellsDocumentPropertyResponse]
  describe 'cells_properties_get_document_property test' do
    it "should work" do
      name = $BOOK1
      property_name = 'Author'
      folder = $TEMPFOLDER
      
      @instance.cells_properties_get_document_property(name, property_name,  { :folder=>folder})
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cells_properties_put_document_property
  # Set/create document property.
  # 
  # @param name The document name.
  # @param property_name The property name.
  # @param [Hash] opts the optional parameters
  # @option opts [CellsDocumentProperty] :property with new property value.
  # @option opts [String] :folder The document folder.
  # @option opts [String] :storage storage name.
  # @return [CellsDocumentPropertyResponse]
  describe 'cells_properties_put_document_property test' do
    it "should work" do
      name = $BOOK1
      property_name = 'Author'
      property = AsposeCellsCloud::CellsDocumentProperty.new({:Name=>'Author',:Value=>'roy'})
      folder = $TEMPFOLDER
      
      @instance.cells_properties_put_document_property(name, property_name, { :property=>property,  :folder=>folder})
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
