=begin
#Web API Swagger specification

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for AsposeCellsCloud::CellsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LightCellsApi' do
  before do
    @instance = AsposeCellsCloud::LightCellsApi.new($client_id,$client_secret,$api_version,$baseurl)
    $VERBOSE = nil
  end

  after do
    # run after each test
  end

  describe 'lite_cells_unit get metadata test' do
    it "should work" do
      files = {}      
      name = $DataSourceXlsx
      files[name] = ::File.open(File.expand_path("data/"+name),"r") 
      name =$AssemblyTestXlsx 
      files[name] = ::File.open(File.expand_path("data/"+name),"r")
     
      result = @instance.get_metadata(files)

      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      end
  end
  describe 'lite_cells_unit delete metadata test' do
    it "should work" do
      files = {}      
      name = $DataSourceXlsx
      files[name] = ::File.open(File.expand_path("data/"+name),"r") 
      name =$AssemblyTestXlsx 
      files[name] = ::File.open(File.expand_path("data/"+name),"r")
     
      result = @instance.delete_metadata(files)

      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      end
  end
  describe 'lite_cells_unit update metadata test' do
    it "should work" do
      files = {}      
      name = $DataSourceXlsx
      files[name] = ::File.open(File.expand_path("data/"+name),"r") 
      name =$AssemblyTestXlsx 
      files[name] = ::File.open(File.expand_path("data/"+name),"r")
      document_property = AsposeCellsCloud::CellsDocumentProperty.new( {:Name=>'test',:Value=>'value'})      
      document_properties = Array.new(1)
      document_properties[0] =document_property
      puts document_property.to_json
      result = @instance.post_metadata(files,document_properties)

      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      end
  end
end

