=begin
#Web API Swagger specification

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AsposeCellsCloud::ShapeOperateParameter
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ShapeOperateParameter' do
  before do
    # run before each test
    @instance = AsposeCellsCloud::ShapeOperateParameter.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShapeOperateParameter' do
    it 'should create an instance of ShapeOperateParameter' do
      expect(@instance).to be_instance_of(AsposeCellsCloud::ShapeOperateParameter)
    end
  end
  describe 'test attribute "operate_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "shape"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

