require 'spec_helper'
require 'json'

# Unit tests for AsposeCellsCloud::CellsTaskApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CellsTaskApi' do
  before do
     @instance = AsposeCellsCloud::CellsApi.new($client_id,$client_secret,"v3.0",$baseurl)
  end

  after do
    # run after each test
  end


  # unit tests for one case

  describe 'cells_get_worksheet_cell test' do
    it "should work" do
      name = $BOOK1
      sheet_name = $SHEET1
      cell_or_method_name = 'firstcell'
      folder = $TEMPFOLDER
      storage = nil
      result = @instance.upload_file( folder+"/"+name,  ::File.open(File.expand_path("data/"+name),"r") {|io| io.read(io.size) })
      expect(result.uploaded.size).to  be > 0
      result = @instance.cells_get_worksheet_cell(name, sheet_name, cell_or_method_name,  { :folder=>folder})
      print(result[0])
      print(result[1])
      print(result[2])
      #expect(result.code).to eql(200)
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
