=begin
#Web API Swagger specification

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for AsposeCellsCloud::CellsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CellsConvertApi' do
  before do
    @instance = AsposeCellsCloud::CellsApi.new($client_id,$client_secret,$api_version,$baseurl)
    $VERBOSE = nil
  end

  after do
    # run after each test
  end

  describe 'cells_unit test' do
    it "should work" do
      result = @instance.post_convert_workbook_to_docx(::File.open(File.expand_path("data/"+ $BOOK1),"r")  )
    end
  end
  describe 'cells_unit test' do
    it "should work" do
      result = @instance.post_convert_workbook_to_png(::File.open(File.expand_path("data/"+ $BOOK1),"r") )
    end
  end
  describe 'cells_unit test' do
    it "should work" do
      result = @instance.post_convert_workbook_to_pdf(::File.open(File.expand_path("data/"+ $BOOK1),"r")  )
    end
  end

  describe 'cells_unit test' do
    it "should work" do
      result = @instance.post_convert_workbook_to_pptx(::File.open(File.expand_path("data/"+ $BOOK1),"r")  )
    end
  end
  describe 'cells_unit test' do
    it "should work" do
      result = @instance.post_convert_workbook_to_html(::File.open(File.expand_path("data/"+ $BOOK1),"r") )
    end
  end
  describe 'cells_unit test' do
    it "should work" do
      result = @instance.post_convert_workbook_to_markdown(::File.open(File.expand_path("data/"+ $BOOK1),"r")  )
    end
  end
  describe 'cells_unit test' do
    it "should work" do
      result = @instance.post_convert_workbook_to_json(::File.open(File.expand_path("data/"+ $BOOK1),"r")  )
    end
  end
  describe 'cells_unit test' do
    it "should work" do
      result = @instance.post_convert_workbook_to_sql(::File.open(File.expand_path("data/"+ $BOOK1),"r")  )
    end
  end
  describe 'cells_unit test' do
    it "should work" do
      result = @instance.post_convert_workbook_to_csv(::File.open(File.expand_path("data/"+ $BOOK1),"r")  )
    end
  end
end

