name: Aspose Cells Cloud SDK for Ruby

on:
  push:
    branches: [  master ]
  pull_request:
    branches: [  master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CellsCloudClientId: ${{ secrets.PRODUCTCLIENTID }}
      CellsCloudClientSecret: ${{ secrets.PRODUCTCLIENTSECRET }}
    strategy:
      matrix:
        ruby-version: [ "3.1"] 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true  

    - name: Install Dependencies
      run: |
        gem install bundler  
        bundle install
        gem build aspose_cells_cloud.gemspec
        gem install aspose_cells_cloud-*.gem

    - name: Run examples
      run: |
        cd examples
        ruby ./Example_QuickStart.rb
  

